version: "3"
x-app: &app
  env_file:
    - .env
services:
  go:
    <<: *app
    volumes:
      - ./app:/app:cached
    tty: true
    command: /bin/bash
    build:
      context: .
  redis:
    <<: *app
    image: "redis:latest"
    ports:
      - "6379:6379"
    volumes:
      - "./docker/redis:/data"
