version: '3'
x-app: &app
  build:
    context: .
  env_file:
    - .env
  environment:
    KVS_HOST: kvs
services:
  app:
    <<: *app
    volumes:
        - ./app:/app:cached
    working_dir: /app
    depends_on:
      - kvs
  kvs:
    image: redis:6.0
    ports:
      - "6379:6379"
    volumes:
      - "./docker/redis:/data"
