version: "3"
services:
  go:
    volumes:
      - ./app:/app:cached
    tty: true
    command: /bin/bash
    build:
      context: .
  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"
    volumes:
      - "./docker/redis:/data"
