version: "3.7"

services:
  bot:
    build:
      context: ./app
    depends_on:
      - kvs
    command: bash -c "python ./application.py"
    volumes:
      - ./app:/app:cached
    environment:
      CLIENT_ID: ${CLIENT_ID}
      CLIENT_SECRET: ${CLIENT_SECRET}
      ACCESS_TOKEN: ${ACCESS_TOKEN}
      KVS_HOST: ${KVS_HOST}
      KVS_PORT: ${KVS_PORT}
    stdin_open: true
    tty: true
  kvs:
    image: redis:6.0
    ports:
      - "6379:6379"
    volumes:
      - kvs-local:/data

volumes:
  kvs-local:
    driver: "local"
