version: '3'
x-app: &app
  build:
    context: .
services:
  app:
    <<-: *app
    volumes:
        - ./app:/app:cached
    command: yarn watch
  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"
    volumes:
      - "./docker/redis:/data"
