version: "3.7"

x-app: &api-app
  build:
    context: ./app
  depends_on:
    - redis
  environment:
    CLIENT_ID: ${CLIENT_ID}
    CLIENT_SECRET: ${CLIENT_SECRET}
    ACCESS_TOKEN: ${ACCESS_TOKEN}
    REDIS_HOST: ${REDIS_HOST}
    REDIS_PORT: ${REDIS_PORT}
  volumes:
    - ./app:/app:cached
services:
  bot:
    <<: *api-app
    command: bash -c "python ./application.py"
    stdin_open: true
    tty: true
  redis:
    image: redis:6.0
    ports:
      - "6379:6379"
    volumes:
      - kvs-local:/data

volumes:
  kvs-local:
    driver: "local"
